DELETE FROM training.task_tests WHERE module_name = 'functions';

INSERT INTO training.task_tests
    (module_name, task_no, test_no, test_name, actual_sql, expected_sql)
VALUES
('functions', 1, 1, 'Склейка и очистка имени',
 $q$SELECT to_jsonb(training.fn_01_full_name('  Ivan ', ' Petrov  '))$q$,
 $q$SELECT to_jsonb('Ivan Petrov'::text)$q$),
('functions', 2, 1, 'Налог и округление',
 $q$SELECT to_jsonb(training.fn_02_add_tax(199.99, 20))$q$,
 $q$SELECT to_jsonb(239.99::numeric)$q$),
('functions', 3, 1, 'Безопасное преобразование текста',
 $q$SELECT jsonb_build_array(training.fn_03_safe_int('42'), training.fn_03_safe_int('oops'), training.fn_03_safe_int(NULL))$q$,
 $q$SELECT '[42, null, null]'::jsonb$q$),
('functions', 4, 1, 'Извлечение года',
 $q$SELECT to_jsonb(training.fn_04_order_year(TIMESTAMP '2018-07-15 12:00:00'))$q$,
 $q$SELECT to_jsonb(2018)$q$),
('functions', 5, 1, 'Длительность доставки',
 $q$SELECT to_jsonb(training.fn_05_delivery_days((SELECT order_id FROM staging.orders WHERE delivered_to_customer_at IS NOT NULL ORDER BY order_id LIMIT 1)))$q$,
 $q$SELECT to_jsonb((SELECT (delivered_to_customer_at::date - purchased_at::date) FROM staging.orders WHERE delivered_to_customer_at IS NOT NULL ORDER BY order_id LIMIT 1))$q$),
('functions', 6, 1, 'Полная стоимость заказа',
 $q$SELECT to_jsonb(training.fn_06_order_total((SELECT order_id FROM staging.order_items ORDER BY order_id LIMIT 1)))$q$,
 $q$SELECT to_jsonb((SELECT round(sum(price + freight_value), 2) FROM staging.order_items WHERE order_id = (SELECT order_id FROM staging.order_items ORDER BY order_id LIMIT 1)))$q$),
('functions', 7, 1, 'Количество заказов покупателя',
 $q$SELECT to_jsonb(training.fn_07_customer_orders((SELECT customer_unique_id FROM mart.customer_summary ORDER BY customer_unique_id LIMIT 1)))$q$,
 $q$SELECT to_jsonb((SELECT orders_count FROM mart.customer_summary ORDER BY customer_unique_id LIMIT 1))$q$),
('functions', 8, 1, 'Категория платежа',
 $q$SELECT jsonb_build_array(training.fn_08_payment_label(50), training.fn_08_payment_label(250), training.fn_08_payment_label(900))$q$,
 $q$SELECT '["small", "medium", "large"]'::jsonb$q$),
('functions', 9, 1, 'Признак опоздания',
 $q$SELECT to_jsonb(training.fn_09_is_late((SELECT order_id FROM mart.order_finance WHERE delivered_to_customer_at IS NOT NULL ORDER BY order_id LIMIT 1)))$q$,
 $q$SELECT to_jsonb((SELECT delivered_late FROM mart.order_finance WHERE delivered_to_customer_at IS NOT NULL ORDER BY order_id LIMIT 1))$q$),
('functions', 10, 1, 'Заказы по штату',
 $q$SELECT to_jsonb(training.fn_10_state_order_count('SP'))$q$,
 $q$SELECT to_jsonb((SELECT count(*) FROM staging.orders o JOIN staging.customers c USING (customer_id) WHERE c.state = 'SP'))$q$),
('functions', 11, 1, 'Табличная функция по диапазону дат',
 $q$SELECT to_jsonb((SELECT count(*) FROM training.fn_11_orders_between(DATE '2018-01-01', DATE '2018-02-01')))$q$,
 $q$SELECT to_jsonb((SELECT count(*) FROM staging.orders WHERE purchased_at >= DATE '2018-01-01' AND purchased_at < DATE '2018-02-01'))$q$),
('functions', 12, 1, 'Параметр со значением по умолчанию',
 $q$SELECT jsonb_build_array((SELECT count(*) FROM training.fn_12_top_customers()), (SELECT count(*) FROM training.fn_12_top_customers(3)))$q$,
 $q$SELECT '[10, 3]'::jsonb$q$),
('functions', 13, 1, 'Выручка категории',
 $q$SELECT to_jsonb(training.fn_13_category_revenue('bed_bath_table'))$q$,
 $q$SELECT to_jsonb(coalesce((SELECT round(sum(revenue), 2) FROM mart.product_sales WHERE product_category_name = 'bed_bath_table'), 0::numeric))$q$),
('functions', 14, 1, 'Набор строк со статистикой статусов',
 $q$SELECT to_jsonb((SELECT sum(orders_count) FROM training.fn_14_order_status_summary()))$q$,
 $q$SELECT to_jsonb((SELECT count(*) FROM staging.orders))$q$),
('functions', 15, 1, 'LTV покупателя',
 $q$SELECT to_jsonb(training.fn_15_customer_ltv((SELECT customer_unique_id FROM mart.customer_summary ORDER BY lifetime_value DESC NULLS LAST LIMIT 1)))$q$,
 $q$SELECT to_jsonb((SELECT lifetime_value FROM mart.customer_summary ORDER BY lifetime_value DESC NULLS LAST LIMIT 1))$q$),
('functions', 16, 1, 'JSON с размерами товара',
 $q$SELECT training.fn_16_product_dimensions((SELECT product_id FROM staging.products WHERE weight_g IS NOT NULL ORDER BY product_id LIMIT 1)) - 'product_id'$q$,
 $q$SELECT to_jsonb(x) FROM (SELECT weight_g, length_cm, height_cm, width_cm FROM staging.products WHERE weight_g IS NOT NULL ORDER BY product_id LIMIT 1) x$q$),
('functions', 17, 1, 'Нормализация города',
 $q$SELECT to_jsonb(training.fn_17_normalize_city('  São   Paulo  '))$q$,
 $q$SELECT to_jsonb('são paulo'::text)$q$),
('functions', 18, 1, 'Именованный аргумент и дата отсчёта',
 $q$SELECT to_jsonb(training.fn_18_days_from_purchase((SELECT order_id FROM staging.orders ORDER BY order_id LIMIT 1), DATE '2020-01-01'))$q$,
 $q$SELECT to_jsonb((SELECT DATE '2020-01-01' - purchased_at::date FROM staging.orders ORDER BY order_id LIMIT 1))$q$),
('functions', 19, 1, 'Процентное изменение и деление на ноль',
 $q$SELECT jsonb_build_array(training.fn_19_percent_change(50, 75), training.fn_19_percent_change(0, 10))$q$,
 $q$SELECT '[50.00, null]'::jsonb$q$),
('functions', 20, 1, 'Массив как входной параметр',
 $q$SELECT to_jsonb((SELECT count(*) FROM training.fn_20_existing_orders(ARRAY(SELECT order_id FROM staging.orders ORDER BY order_id LIMIT 4))))$q$,
 $q$SELECT to_jsonb(4)$q$),
('functions', 21, 1, 'Помесячная выручка',
 $q$SELECT to_jsonb((SELECT round(sum(revenue), 2) FROM training.fn_21_monthly_revenue(2017)))$q$,
 $q$SELECT to_jsonb((SELECT round(sum(revenue), 2) FROM mart.monthly_sales WHERE extract(year FROM month) = 2017))$q$),
('functions', 22, 1, 'Ранг продавца',
 $q$SELECT to_jsonb(training.fn_22_seller_rank((SELECT seller_id FROM staging.order_items GROUP BY seller_id ORDER BY sum(price) DESC LIMIT 1)))$q$,
 $q$SELECT to_jsonb(1::bigint)$q$),
('functions', 23, 1, 'Профиль покупателя в JSON',
 $q$SELECT training.fn_23_customer_profile((SELECT customer_unique_id FROM mart.customer_summary ORDER BY customer_unique_id LIMIT 1))$q$,
 $q$SELECT to_jsonb(x) FROM (SELECT customer_unique_id, orders_count, lifetime_value FROM mart.customer_summary ORDER BY customer_unique_id LIMIT 1) x$q$),
('functions', 24, 1, 'Фильтры из JSON',
 $q$SELECT to_jsonb((SELECT count(*) FROM training.fn_24_search_orders('{"status":"delivered","state":"SP"}'::jsonb)))$q$,
 $q$SELECT to_jsonb((SELECT count(*) FROM staging.orders o JOIN staging.customers c USING (customer_id) WHERE o.order_status='delivered' AND c.state='SP'))$q$),
('functions', 25, 1, 'Динамический SQL и идентификаторы',
 $q$SELECT to_jsonb(training.fn_25_table_row_count('raw', 'orders'))$q$,
 $q$SELECT to_jsonb((SELECT count(*) FROM raw.orders))$q$),
('functions', 26, 1, 'VOLATILE-функция с побочным эффектом',
 $q$SELECT jsonb_build_array(training.fn_26_audit_event('auto_test', '{"ok":true}'::jsonb) > 0, (SELECT provolatile='v' FROM pg_proc WHERE oid='training.fn_26_audit_event(text,jsonb)'::regprocedure))$q$,
 $q$SELECT '[true, true]'::jsonb$q$),
('functions', 27, 1, 'Корректная категория volatility',
 $q$SELECT jsonb_build_array(training.fn_27_order_count(), (SELECT provolatile='s' FROM pg_proc WHERE oid='training.fn_27_order_count()'::regprocedure))$q$,
 $q$SELECT jsonb_build_array((SELECT count(*) FROM staging.orders), true)$q$),
('functions', 28, 1, 'Расстояние по координатам',
 $q$SELECT jsonb_build_array(round(training.fn_28_distance_km(0,0,0,0),3), round(training.fn_28_distance_km(0,0,0,1),3))$q$,
 $q$SELECT '[0.000, 111.195]'::jsonb$q$),
('functions', 29, 1, 'Когортный retention',
 $q$SELECT to_jsonb(training.fn_29_cohort_retention(DATE '2017-01-01', 1) BETWEEN 0 AND 100)$q$,
 $q$SELECT 'true'::jsonb$q$),
('functions', 30, 1, 'Итоговая сегментация покупателя',
 $q$SELECT to_jsonb(training.fn_30_customer_segment((SELECT customer_unique_id FROM mart.customer_summary ORDER BY lifetime_value DESC NULLS LAST LIMIT 1)))$q$,
 $q$SELECT to_jsonb('VIP'::text)$q$);
