from pathlib import Path
import nbformat as nbf

ROOT=Path(__file__).resolve().parent.parent
(ROOT/"notebooks").mkdir(parents=True,exist_ok=True)
MODULES=[
("01","hdfs_model","Архитектура HDFS и файловая модель",["NameNode metadata","DataNode storage","namespace","block size","replication","rack awareness","write pipeline","read path","checksums","heartbeats","block reports","safe mode","HA concepts","federation","small files","append model","rename atomicity","consistency","local vs HDFS","URI schemes","capacity","used vs remaining","under-replication","corrupt blocks","fsck","snapshots","trash","quotas","Web UI","architecture audit"]),
("02","hdfs_cli","HDFS CLI и управление данными",["mkdir","put","copyFromLocal","get","cat","text","head","tail","ls","du","count","stat","test","cp","mv","rm to trash","expunge","touchz","appendToFile","getmerge","setrep","checksum","find","glob","permissions","owner","ACL","snapshot commands","distcp concept","CLI pipeline"]),
("03","formats","Форматы, Parquet и сжатие",["row format","column format","CSV limits","JSON lines","Avro schema","Parquet schema","row groups","pages","column chunks","statistics","predicate pushdown","column pruning","dictionary encoding","RLE","Snappy","Gzip","splittability","schema evolution","nullable columns","logical types","partition columns","file metadata","pyarrow inspection","small files","target file size","compaction","compression tradeoff","corrupt file","schema reconciliation","format decision"]),
("04","hive_ddl","Hive DDL и таблицы",["database","external table","managed table","location","Parquet table","typed schema","describe formatted","show create","load data","insert into","insert overwrite","CTAS","view","temporary view","drop external","drop managed","alter rename","add columns","table properties","null handling","SerDe","text table","repair table","metadata vs data","schema mismatch","decimal type","timestamp type","array type","map type","DDL audit"]),
("05","partitioning","Партиционирование и оптимизация Hive",["partition key","static partition","dynamic partition","add partition","drop partition","MSCK repair","partition discovery","partition pruning","explain","predicate placement","date partition","multi-level partition","over-partitioning","small partitions","partition stats","table stats","analyze","column stats","join plan","map join","sort by","distribute by","cluster by","order by","bucketing","bucket count","sampling","compaction","optimized eBay table","plan audit"]),
("06","operations","Права и эксплуатация HDFS",["POSIX mode","chmod symbolic","chmod octal","chown","chgrp","umask","ACL user","ACL group","default ACL","mask ACL","getfacl","remove ACL","shared raw layer","private user layer","sticky bit","trash policy","space quota","namespace quota","setrep operations","decommission concept","balancer concept","safemode check","fsck health","block locations","DataNode report","NameNode JMX","audit logs","least privilege","recovery drill","operations checklist"]),
("07","etl_quality","Batch ETL и качество данных",["landing table","staging table","typed projection","required fields","range check","domain check","duplicate key","reject view","accepted view","row reconciliation","null profile","distinct profile","min max profile","partition completeness","file completeness","schema validation","freshness","idempotent overwrite","incremental append","watermark","late data","dedup snapshot","current record","history record","daily aggregate","quality summary","publish gate","rerun partition","lineage columns","batch pipeline"]),
("08","capstone","Итоговый Hadoop-проект eBay",["project namespace","raw inventory","schema inventory","external raw","partition repair","profile rows","profile nulls","profile keys","clean staging","reject records","deduplicate","optimized parquet","partition strategy","file sizing","seller dimension","category dimension","listing fact","daily snapshot","price metric","shipping metric","quality mart","reconciliation","permission model","replication audit","storage audit","query plan","incremental day","rerun proof","documentation view","final acceptance"])]

THEORY={"hdfs_model":"HDFS хранит большие неизменяемые файлы блоками: NameNode держит namespace и карту блоков, DataNode — байты. Репликация обеспечивает доступность, но не является резервной копией. Малые файлы расходуют metadata и создают накладные расходы.","hdfs_cli":"CLI изменяет удалённый namespace, а не локальную файловую систему. Всегда проверяйте URI, владельца, права, код возврата и результат командой test/stat/count.","formats":"Формат определяет стоимость чтения. Parquet хранит колонки, статистики и row groups; predicate pushdown и column pruning уменьшают I/O. Сжатие выбирают вместе с splittability и CPU.","hive_ddl":"Hive-таблица — metadata над файлами. EXTERNAL отделяет жизненный цикл данных от каталога, managed связывает их. LOCATION, схема и физический Parquet должны согласовываться.","partitioning":"Партиция — каталог, выбранный значением ключа. Pruning работает только при предикате по partition column. Слишком много мелких партиций меняет data scan на metadata bottleneck.","operations":"HDFS проверяет owner/group/mode и ACL на каждом компоненте пути. Эксплуатация включает fsck, replication, quotas, capacity и восстановление; chmod 777 не является архитектурой доступа.","etl_quality":"Batch обязан быть идемпотентным и сверяемым: read = accepted + rejected, ключи уникальны, публикация атомарна. Watermark обновляют только после успешной порции.","capstone":"Итоговый слой начинается с контракта данных, затем строит raw→staging→core→quality. Каждая оптимизация подтверждается планом, а каждая загрузка — reconciliation."}

THEORY_SECTIONS={
"hdfs_model":[("Namespace и metadata","NameNode хранит дерево каталогов, владельцев, права и соответствие файл→блоки. Он не проксирует байты клиента: после получения адресов блоков клиент общается с DataNode."),("Блоки и репликация","Большой файл режется на блоки. Репликация 2 означает две копии каждого блока на разных DataNode; потеря узла не равна потере файла, но ошибочное удаление реплицируется мгновенно."),("Чтение и запись","При записи NameNode выбирает pipeline DataNode, пакеты проходят по цепочке, подтверждения идут обратно. Файл становится устойчивым только после подтверждений и закрытия."),("Сбои","Heartbeat показывает живость узла, block report — фактический состав блоков. Недореплицированные блоки восстанавливаются асинхронно; fsck проверяет целостность namespace."),("Цена малых файлов","Каждый файл и блок потребляет heap NameNode и создаёт отдельную задачу чтения. Тысячи маленьких Parquet-файлов часто хуже одного разумного row group.")],
"hdfs_cli":[("Две файловые системы","Локальный путь и HDFS URI — разные пространства. put/get пересекают границу; cp/mv работают внутри HDFS."),("Коды возврата","Успех команды подтверждает exit code 0. `-test -e/-d/-f/-r/-w` удобен для идемпотентных скриптов без разбора текста."),("Размеры","`du` показывает байты данных, `count` — каталоги/файлы/байты, фактический расход учитывает replication. Не путайте logical и physical size."),("Удаление","rm обычно перемещает данные в Trash пользователя. skipTrash и expunge требуют осознанности: восстановимость меняется."),("Автоматизация","Команды должны быть повторяемыми: mkdir -p, put -f только когда перезапись задумана, явные пути без опасных glob и проверка результата.")],
"formats":[("Строка и колонка","CSV/JSON удобны на границе, но читают строку целиком. Parquet организует данные по колонкам и позволяет пропускать ненужные столбцы."),("Физика Parquet","Файл состоит из row groups, column chunks и pages. Footer содержит схему и статистики; слишком мелкие row groups ухудшают throughput."),("Pushdown","Фильтр может использовать min/max статистики и не читать row group. Это работает только при совместимых типах и предикатах."),("Кодирование и compression","Dictionary/RLE уменьшают повторяющиеся значения, Snappy быстро распаковывается, Gzip сильнее сжимает ценой CPU. Выбор измеряют на своём workload."),("Эволюция схемы","Добавление nullable-колонки обычно совместимо, изменение типа — нет. Читатель согласует схемы файлов, поэтому mixed schema требует теста.")],
"hive_ddl":[("Metastore","Hive хранит DDL, schema, location и partitions в metastore; строки остаются в HDFS. DROP затрагивает данные по-разному для managed и external."),("Схема при чтении","Schema-on-read не исправляет плохие данные: несовпадение физического Parquet-типа и DDL приводит к NULL или ошибке."),("LOCATION","Путь — часть контракта. Две таблицы могут смотреть на одни файлы, поэтому владение и жизненный цикл нужно определить заранее."),("Запись","INSERT INTO добавляет, INSERT OVERWRITE заменяет выбранную область. CTAS удобен, но типы и свойства следует проверить SHOW CREATE TABLE."),("Сложные типы","ARRAY, MAP и STRUCT сохраняют вложенность, однако усложняют совместимость и запросы. Выбор должен следовать форме события.")],
"partitioning":[("Partition pruning","Hive читает только каталоги партиций, если предикат явно ограничивает partition column. Функция над ключом может помешать pruning."),("Кардинальность ключа","Дата часто подходит, itemid почти всегда слишком детален. Количество каталогов и файлов должно оставаться управляемым."),("Статика и динамика","Static partition фиксируется в DDL вставки; dynamic берётся из данных. Ошибка режима способна создать неожиданно много каталогов."),("Статистика","ANALYZE собирает row count и column statistics. Без неё стоимость JOIN и порядок таблиц оцениваются вслепую."),("Распределение","DISTRIBUTE BY управляет reducer, SORT BY сортирует внутри него, ORDER BY требует глобального порядка. Bucketing полезен лишь при согласованной записи и чтении.")],
"operations":[("Авторизация","Для доступа нужны execute на всех родительских каталогах и нужное право на объекте. ACL дополняет POSIX mode, а mask ограничивает эффективные права."),("Владение","chown — административная операция; приложениям обычно дают групповую роль или ACL. Общий raw должен быть read-only."),("Quotas","Namespace quota ограничивает число имён, space quota — физический расход с учётом replication. Они останавливают runaway pipeline до заполнения диска."),("Наблюдаемость","dfsadmin -report показывает узлы и capacity, fsck — блоки, JMX — метрики NameNode. Один зелёный endpoint не доказывает здоровье данных."),("Восстановление","Trash, snapshots и replication решают разные задачи. Runbook должен содержать точные признаки сбоя, безопасные команды и проверку после восстановления.")],
"etl_quality":[("Слои","Landing фиксирует вход, staging типизирует, core применяет бизнес-ключи, quality публикует доказательства. Raw не исправляют задним числом."),("Контракты","Проверяйте обязательность, тип, диапазон, domain, уникальность и ссылочную целостность. Reject сохраняет причину, исходную строку и run_id."),("Идемпотентность","Повтор одной порции не меняет итог. Обычно это overwrite партиции или MERGE по ключу, а не безусловный append."),("Инкремент","Watermark хранит подтверждённую границу. Опоздавшие события требуют overlap/reprocessing; обновлять watermark до publish нельзя."),("Reconciliation","read = accepted + rejected, target delta согласуется с accepted, агрегаты источника и цели совпадают в допустимой точности.")],
"capstone":[("Контракт проекта","Зафиксируйте владельца, grain, ключ, SLA, schema, partition strategy и правила качества до реализации."),("Поток данных","Raw inventory → external raw → typed staging → deduplicated core → dimensions/fact → quality mart. Каждый переход имеет контроль."),("Физический дизайн","Parquet, Snappy, дневная partition и целевой размер файлов выбираются по объёму и запросам, а не по привычке."),("Эксплуатация","Проект включает права, replication, повтор порции, late data, мониторинг и runbook. Таблица без режима обновления не завершена."),("Приёмка","Докажите schema, counts, uniqueness, reconciliation, pruning, читаемость, права и идемпотентный rerun на одной дате.")]
}

def md(x):return nbf.v4.new_markdown_cell(x)
def code(x):return nbf.v4.new_code_cell(x)
for no,key,title,topics in MODULES:
 theory="\n\n".join(f"### {i}. {name}\n\n{text}" for i,(name,text) in enumerate(THEORY_SECTIONS[key],1))
 helper='''import json, os, subprocess, tempfile\n\ndef save_evidence(module, task, command, observation, explanation):\n    user=os.environ.get("HDFS_USER", os.environ.get("HADOOP_USER_NAME", "student"))\n    target=f"/user/{user}/hadoop_training/evidence/{module}/task_{task:02d}.json"\n    payload={"module":module,"task":task,"command":command,"observation":observation,"explanation":explanation}\n    with tempfile.NamedTemporaryFile("w",encoding="utf-8",delete=False,suffix=".json") as f:\n        json.dump(payload,f,ensure_ascii=False,indent=2); local=f.name\n    subprocess.run(["hdfs","dfs","-mkdir","-p",target.rsplit("/",1)[0]],check=True)\n    subprocess.run(["hdfs","dfs","-put","-f",local,target],check=True)\n    os.unlink(local)\n    print(target)'''
 c=[md(f"# {title} — 30 заданий\n\nПрактика выполняется на eBay в `/data/raw/ebay`. Решений нет."),md("## Ментальная модель\n\n"+THEORY[key]),md("## Подробная теория\n\n"+theory),md("## Стенд\n\nNameNode `namenode:8020`, два DataNode, HiveServer2 `hiveserver2:10000`. Личные артефакты не создаются в общем read-only raw-слое."),md("## Как сдаётся задание\n\nВалидатор проверяет артефакт и JSON-доказательство. В `command` запишите фактическую команду, в `observation` — измеренный результат, в `explanation` — почему он получился. Минимальная длина защищает от пустых ответов; содержательный смысл остаётся вашей ответственностью."),code(helper)]
 for i,t in enumerate(topics,1):
  artifact=(f"`/user/$HDFS_USER/hadoop_training/{key}/task_{i:02d}` с минимум одним файлом" if key in {"hdfs_model","hdfs_cli","formats","operations"} else f"Hive-объект `{ {'hive_ddl':'hv','partitioning':'pt','etl_quality':'dq','capstone':'cp'}[key]}_{i:02d}` в личной БД")
  c += [md(f"### Задание {i}. {t}\n\nСоздайте {artifact}. **До запуска:** запишите ожидаемый результат. **После:** измерьте число файлов/строк, свойства или права, относящиеся к теме `{t}`. Проверьте повторный запуск и не изменяйте `/data/raw/ebay`.\n\n<details><summary>Подсказка</summary>\n\nВыполняйте одно изменение за шаг. Сравните состояние до/после независимой командой, затем сохраните evidence.\n\n</details>"),code("# Ваши команды здесь\n# Для shell используйте !hdfs dfs ... или %%bash\n# Для Hive используйте !beeline ...\n# save_evidence(...)") ,code(f"!python3 /opt/lab/hadoop-training/check_task.py {key} {i}")]
 c += [md("## Итог\n\nВсе 30 проверок должны возвращать PASS. Удалять чужие или raw-данные запрещено.")]
 nbf.write(nbf.v4.new_notebook(cells=c,metadata={"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"}}),ROOT/"notebooks"/f"{no}_{key}_30_Tasks.ipynb")
mapcells=[md("# Hadoop Course Map\n\n8 модулей, 240 заданий на реальном eBay Parquet. Готовых решений нет; каждое упражнение подтверждается артефактом и evidence."),md("## Архитектура стенда\n\n```text\nJupyter ── hdfs://namenode:8020 ── DataNode 1\n   │                 └──────────── DataNode 2\n   └── HiveServer2 ── Hive Metastore ── PostgreSQL\n```\n\nОбщий `/data/raw/ebay` доступен только для чтения. Практика HDFS находится в `/user/<user>/hadoop_training`, Hive — в `<user>_db`."),md("## Схема eBay\n\nОдна строка — наблюдение объявления `itemid` на дату `snapshot_dt`. Основные группы колонок: товар (`title`, `price`, `item_condition`), категории (`category_id/name`, `sub_category_*`), продавец (`seller_name`, feedback), местоположение, доставка, валюта и buying options. Датасет партиционирован каталогами `snapshot_dt=YYYY-MM-DD`, хранится в Parquet/Snappy."),md("## Модули\n\n"+"\n".join(f"{i}. **{title}** — 30 заданий" for i,(_,_,title,_) in enumerate(MODULES,1))),md("## Порядок работы\n\nИдите последовательно: архитектура → CLI → форматы → Hive → оптимизация → эксплуатация → ETL → проект. Для каждого задания: прогноз → команда → независимое измерение → `save_evidence` → checker. FAIL нельзя заменять ручной отметкой.")]
nbf.write(nbf.v4.new_notebook(cells=mapcells,metadata={"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"}}),ROOT/"notebooks"/"00_Hadoop_Course_Map.ipynb")
