import os
from pathlib import Path
import nbformat as nbf

ROOT=Path(__file__).resolve().parent.parent
OUT=Path(os.environ.get("GREENPLUM_COURSE_OUTPUT",ROOT/"notebooks"))
OUT.mkdir(parents=True,exist_ok=True)
def md(x): return nbf.v4.new_markdown_cell(x)
def code(x): return nbf.v4.new_code_cell(x)
meta={"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"}}
connect="%load_ext sql\n%config SqlMagic.displaylimit = 100\n%sql postgresql+psycopg2://gpadmin@cbdb-coordinator:5432/moex"

course=nbf.v4.new_notebook(cells=[
 md("# Курс Cloudberry / Greenplum\n\nКурс работает на локальном четырёхсегментном кластере. Решения создаются в `m_razhin`, проверки — в `greenplum_training`; используются общий HDFS, PXF и GPFDIST."),
 md("## Модули\n\n| № | Ноутбук | Тема | Задания/тесты |\n|---|---|---|---|\n|00|[Architecture](00_Architecture_and_Infrastructure.ipynb)|Архитектура и инфраструктура|введение|\n|01|[Distribution](01_Distribution_30_Tasks.ipynb)|Распределение, skew, Motion|30/60|\n|02|[Storage](02_Storage_Partitioning_30_Tasks.ipynb)|Хранение, compression, partitions, exchange|30/60|\n|03|[Optimization](03_Query_Plans_Optimization_30_Tasks.ipynb)|Планы и оптимизация|30/60|\n|04|[GPFDIST](04_GPFDIST_30_Tasks.ipynb)|GPFDIST и CSV pipeline|30/60|\n|05|[PXF](05_PXF_HDFS_Parquet_30_Tasks.ipynb)|PXF, HDFS, Parquet|30/60|\n|06|[ETL](06_ETL_30_Tasks.ipynb)|Full/incremental ETL, SCD, retry|30/60|\n|07|[Data marts](07_Data_Marts_30_Tasks.ipynb)|MOEX facts/dimensions/marts|30/60|\n|08|[Administration](08_Administration_30_Tasks.ipynb)|Health, locks, maintenance, runbooks|30/60|\n\nВсего: **240 практических заданий и 480 автоматических тестов**."),
 md("## Правила\n\n- исходные `dds` и HDFS не изменяем;\n- изменяющая практика работает на учебных копиях;\n- готовые решения не публикуются;\n- прогресс сохраняется автоматически."),
 code(connect),
 code("%%sql\nSELECT version();\nSELECT module_name,\n       count(*) AS attempted_tasks,\n       count(*) FILTER (WHERE completed) AS completed_tasks,\n       sum(tests_passed) AS passed_tests,\n       sum(tests_total) AS attempted_tests\nFROM greenplum_training.progress\nGROUP BY module_name\nORDER BY module_name;")
],metadata=meta)
nbf.write(course,OUT/"00_Greenplum_Course_Map.ipynb")

intro=nbf.v4.new_notebook(cells=[
 md("# Архитектура Cloudberry / Greenplum\n\nCoordinator принимает SQL и строит распределённый план. Данные физически разделены между четырьмя primary-сегментами; mirrors и standby обеспечивают отказоустойчивость."),
 code(connect),
 md("## Топология\n\n```text\nJupyter → coordinator cdw\n  ├─ content 0,1 → sdw1; mirrors → sdw2\n  └─ content 2,3 → sdw2; mirrors → sdw1\nstandby → scdw\nPXF на sdw1/sdw2 → общий HDFS\n```\n\n`content=-1` обозначает coordinator; `p` — primary, `m` — mirror."),
 code("%%sql\nSELECT dbid,content,role,preferred_role,mode,status,hostname,port\nFROM gp_segment_configuration ORDER BY dbid;"),
 md("## PostgreSQL и Greenplum: главное различие\n\nPostgreSQL обычно выполняет запрос одним серверным процессом над одним экземпляром хранения. Greenplum сохраняет знакомый SQL и каталоги PostgreSQL, но распределяет пользовательские данные и вычисления между сегментами. Поэтому логически правильный SQL может иметь совершенно разную стоимость в зависимости от физического распределения.\n\nВ PostgreSQL основным вопросом часто становится «какой индекс использовать?». В Greenplum к нему добавляются вопросы:\n\n- на каких сегментах находятся строки;\n- требуется ли пересылка между сегментами;\n- равномерно ли распределена работа;\n- можно ли выполнить JOIN и агрегацию локально;\n- не ограничивает ли весь запрос один перегруженный сегмент."),
 md("## MPP: shared-nothing\n\nGreenplum — MPP-система (Massively Parallel Processing) с архитектурой shared-nothing. Каждый primary-сегмент имеет собственный процесс PostgreSQL, память и локальные файлы данных. Сегменты не читают файлы друг друга напрямую. Для совместной операции строки передаются через interconnect.\n\nПреимущество — горизонтальный параллелизм: увеличение числа сегментов добавляет CPU, память и пропускную способность хранения. Цена — стоимость сетевого обмена и необходимость равномерно распределить данные."),
 md("## Coordinator\n\nCoordinator принимает клиентское соединение, разбирает SQL, проверяет права, строит глобальный план и управляет выполнением. Он не является местом хранения обычных распределённых таблиц. На coordinator находятся глобальные системные каталоги и служебное состояние.\n\nCoordinator не должен становиться вычислительным узким местом. Операции, которые собирают очень большой результат через `Gather Motion`, переносят работу и трафик к coordinator. Поэтому аналитический запрос обычно должен максимально фильтровать и агрегировать данные на сегментах."),
 md("## Primary, mirror и content\n\n`content` — логический сегмент данных. У каждого content есть primary, который обслуживает запросы, и mirror — синхронная резервная копия. В стенде четыре content: 0–3.\n\n`dbid` идентифицирует конкретный экземпляр процесса, а не логический набор данных. После failover бывший mirror может стать primary, но content останется тем же. `preferred_role` показывает исходно назначенную роль, `role` — текущую.\n\nВ `gp_segment_configuration`:\n\n- `status='u'` — экземпляр доступен;\n- `mode='s'` — primary и mirror синхронизированы;\n- content `-1` — coordinator или standby coordinator."),
 md("## Standby coordinator\n\nStandby хранит копию coordinator-каталогов и журнала, но не обслуживает обычные пользовательские запросы, пока не активирован. Он защищает от потери управляющего узла. Наличие standby не заменяет резервное копирование: логическая ошибка или удаление данных реплицируется вместе с корректными изменениями."),
 md("## Как проходит SELECT\n\n1. Клиент отправляет SQL coordinator.\n2. Parser и analyzer строят дерево запроса и разрешают имена объектов.\n3. Optimizer выбирает порядок JOIN, методы доступа, агрегации и Motion.\n4. План делится на slices в точках Motion.\n5. Coordinator создаёт gang процессов исполнителей на сегментах.\n6. Сегменты параллельно читают локальные строки и обмениваются данными.\n7. Итоговый slice возвращает результат клиенту.\n\nВремя запроса определяется не средним сегментом, а самым медленным участником каждого зависимого этапа."),
 md("## Slices и gangs\n\nSlice — часть плана между операторами Motion. Операторы одного slice могут выполняться конвейерно. Motion создаёт границу producer/consumer: один набор процессов отправляет строки, другой принимает.\n\nGang — группа segment processes, выделенная для slice. В плане номера slices помогают понять порядок распределённого выполнения. Большое число slices не обязательно плохо, но часто указывает на сложную цепочку обменов."),
 md("## Распределённый план\n\nПлан делится на slices. `Gather Motion` собирает строки, `Redistribute Motion` пересылает их по хешу нового ключа, `Broadcast Motion` копирует небольшой набор каждому сегменту. Motion часто определяет стоимость JOIN и GROUP BY."),
 code("%%sql\nEXPLAIN SELECT regioncountry,count(*)\nFROM dds.ext_raw_yndx_metrica_logs GROUP BY regioncountry;"),
 md("## Interconnect\n\nInterconnect — транспорт между segment processes. Через него проходят строки Motion. Даже если таблицы читаются быстро, большой Redistribute или Broadcast может ограничиваться сетью, сериализацией и очередями получателей.\n\nУменьшить трафик помогают ранний фильтр, частичная агрегация на сегментах, совместимое распределение больших таблиц и репликация только действительно маленьких справочников."),
 md("## Системные каталоги\n\nМногие знакомые каталоги PostgreSQL остаются доступными: `pg_class`, `pg_attribute`, `pg_namespace`, `pg_stat_activity`. Greenplum добавляет:\n\n- `gp_segment_configuration` — экземпляры кластера;\n- `gp_distribution_policy` — физическая policy таблиц;\n- `pg_exttable` — внешние таблицы;\n- `gp_toolkit` — диагностические views и функции.\n\nНе изменяйте системные каталоги напрямую. Физические свойства задаются DDL-командами."),
 code("%%sql\nSELECT n.nspname AS schema_name,\n       c.relname AS table_name,\n       pg_get_table_distributedby(c.oid) AS distribution\nFROM pg_class c\nJOIN pg_namespace n ON n.oid=c.relnamespace\nWHERE n.nspname='m_razhin' AND c.relkind='r'\nORDER BY c.relname\nLIMIT 20;"),
 md("## Транзакции и MVCC\n\nGreenplum наследует MVCC PostgreSQL: изменение создаёт новую версию строки, а snapshot определяет видимость. Но транзакция распределена между coordinator и несколькими сегментами. Coordinator координирует согласованный commit.\n\nДолгие транзакции мешают очистке старых версий на множестве сегментов. Массовые изменения следует проектировать как управляемые batch-операции и не оставлять соединение `idle in transaction`."),
 md("## Статистика и optimizer\n\nOptimizer оценивает количество строк, селективность фильтров и стоимость Motion. Без актуальной статистики он может broadcast-ить большой набор, выбрать неудачный порядок JOIN или неверно оценить память. После значительной загрузки выполняют `ANALYZE` нужной таблицы.\n\n`EXPLAIN` показывает оценку, `EXPLAIN ANALYZE` действительно выполняет запрос и показывает фактические строки/время. Изменяющий запрос с `EXPLAIN ANALYZE` также выполняет изменение — это важно помнить."),
 md("## Типы таблиц\n\nВ дальнейших модулях используются:\n\n- heap — привычное построчное изменяемое хранение;\n- append-optimized row — эффективная последовательная загрузка;\n- append-optimized column — чтение выбранных колонок и сжатие;\n- partitioned table — логическое дерево физических частей;\n- external table — данные остаются во внешнем источнике, например HDFS или GPFDIST.\n\nСпособ хранения и distribution policy решают разные задачи и настраиваются совместно."),
 md("## PXF и GPFDIST\n\nPXF — слой доступа сегментов к HDFS и другим внешним системам. Сегменты читают внешние фрагменты параллельно. GPFDIST — высокопроизводительный HTTP-сервер для параллельной загрузки/выгрузки файлов.\n\nPXF не превращает HDFS-файл во внутреннюю таблицу: внешний запрос повторно обращается к источнику. Для часто используемых данных может быть выгодна загрузка во внутреннюю AO column table."),
 md("## Распределение и skew\n\nХеш ключа определяет сегмент. Хороший ключ имеет много значений, равномерную частоту и совпадает с частыми ключами JOIN. Самый загруженный сегмент ограничивает скорость всего запроса."),
 code("%%sql\nSELECT gp_segment_id,count(*) rows_count\nFROM m_razhin.yndx_metrica_logs GROUP BY gp_segment_id ORDER BY 1;"),
 md("## Источники\n\n- `dds.ext_raw_yndx_metrica_logs` — PXF/Метрика;\n- `gpfdist://cdw:8080/countries.csv`;\n- `/data/raw/m_razhin/` — персональный HDFS;\n- `/moex_labs/raw/trades/` — MOEX;\n- `m_razhin` — рабочая схема."),
 code("%%sql\nSET search_path TO m_razhin,public;\nSELECT current_database(),current_user,current_schema();\nSELECT extname,extversion FROM pg_extension ORDER BY 1;"),
 md("## Самопроверка\n\nВсе 10 записей конфигурации должны иметь status `u`; PXF и обе учебные схемы должны существовать."),
 code("%%sql\nSELECT count(*) FILTER(WHERE status='u') up,count(*) total FROM gp_segment_configuration;\nSELECT EXISTS(SELECT 1 FROM pg_extension WHERE extname='pxf') pxf,\nEXISTS(SELECT 1 FROM pg_namespace WHERE nspname='m_razhin') student_schema;")
],metadata=meta)
nbf.write(intro,OUT/"00_Architecture_and_Infrastructure.ipynb")
print(OUT)
