from pathlib import Path
import nbformat as nbf
R=Path(__file__).resolve().parent.parent;(R/'notebooks').mkdir(parents=True,exist_ok=True)
M=[
('01','foundations','Архитектура и основы Spark','driver executors|SparkSession|SparkContext|cluster master|application job stage task|lazy evaluation|action и transformation|lineage|narrow dependency|wide dependency|shuffle|partition|input partition|DAG|fault tolerance|recomputation|local и cluster|serialization|closure|broadcast variable|accumulator|cache|persist levels|unpersist|UI jobs|UI stages|UI storage|configuration|resource sizing|architecture audit'),
('02','dataframes','DataFrame API','read parquet|explicit schema|select|alias|withColumn|drop|cast|filter|null predicates|fillna|dropna|replace|when otherwise|string functions|date functions|array functions|struct|explode|distinct|dropDuplicates|orderBy|limit|sample|randomSplit|unionByName|repartition|coalesce|transform|write parquet|transformation pipeline'),
('03','spark_sql','Spark SQL','temporary view|global temp view|catalog databases|catalog tables|SQL projection|SQL filter|CASE|NULL semantics|string SQL|date SQL|aggregate SQL|GROUP BY|HAVING|CTE|subquery|EXISTS|set operations|complex types|lateral view explode|create table|external table|insert into|insert overwrite|partition DDL|MSCK repair|describe extended|cache table|uncache table|SQL DataFrame parity|SQL pipeline'),
('04','analytics','Агрегации, JOIN и окна','count variants|sum avg|min max|approx distinct|groupBy|pivot|rollup|cube|inner join|left join|left semi|left anti|null-safe join|join cardinality|pre-aggregation|broadcast join|self join|row_number|rank dense_rank|lag lead|running sum|moving average|top N group|first last|percentile|gaps islands|sessions|cohort|retention|analytics mart'),
('05','storage','Партиционирование и хранение','logical partitions|repartition N|repartition key|coalesce|partitionBy write|partition discovery|partition pruning|input files|file count|small files|target size|maxRecordsPerFile|Snappy|Gzip|Parquet schema|mergeSchema|column pruning|predicate pushdown|row group stats|overwrite mode|append mode|dynamic overwrite|saveAsTable|insertInto|bucketBy|sortBy|compaction|schema evolution|storage metrics|optimized dataset'),
('06','performance','Планы и производительность','explain simple|explain formatted|logical plan|optimized plan|physical plan|Catalyst rules|statistics|AQE|shuffle partitions|broadcast threshold|broadcast hint|join strategies|sort merge join|broadcast hash join|shuffle hash join|nested loop|exchange node|sort node|filter pushdown|column pruning plan|cache plan|cache materialization|storage level|skew detection|salting|repartition by range|avoid UDF|pandas UDF concept|benchmark|performance audit'),
('07','quality_etl','Качество, тесты и ETL','schema contract|required columns|type contract|not null|domain check|range check|unique key|duplicate profile|reject frame|accepted frame|row reconciliation|metric reconciliation|assertions|dataframe equality|deterministic sort|idempotent overwrite|incremental partition|watermark|late data|dedup snapshot|latest record|SCD1|SCD2|audit columns|run metadata|quality report|publish gate|rerun test|failure recovery|ETL pipeline'),
('08','capstone','Итоговый Spark-проект eBay','source inventory|source schema|source profile|grain|business key|null profile|duplicate profile|typed staging|reject layer|accepted layer|dedup current|price normalization|shipping normalization|seller dimension|category dimension|listing fact|daily snapshot|price statistics|seller metrics|category metrics|quality mart|partition strategy|file sizing|cache decision|join strategy|plan evidence|incremental day|idempotent rerun|reconciliation|final acceptance')]
THEORY={
'foundations': [('Кластер','Driver строит DAG и координирует executors; executors выполняют tasks и держат cache.'),('Ленивость','Transformation только расширяет lineage. Action запускает job; wide dependency образует shuffle и новую stage.'),('Партиции','Один task обрабатывает одну partition. Число partitions определяет параллелизм и scheduler overhead.'),('Отказы','Spark восстанавливает потерянные partitions по lineage; cache ускоряет повтор, но не заменяет HDFS.'),('UI','Jobs, stages, tasks, shuffle, spill и skew нужно читать вместе, а не судить только по времени.')],
'dataframes':[('Schema','Типы определяют сравнение и кодирование; строковая цена и timestamp дают логически неверные ответы.'),('Columns','Встроенные expressions видимы Catalyst, Python UDF создаёт границу сериализации.'),('NULL','NULL не равен пустой строке и самому себе; применяйте isNull, coalesce и null-safe правила.'),('Shuffle','distinct, orderBy, groupBy и repartition могут передавать данные между executors.'),('Write','До записи задайте mode, partitions, file count, compression и правила schema evolution.')],
'spark_sql':[('Engine','SQL и DataFrame компилируются одним Catalyst и при равной логике имеют одинаковый plan.'),('Catalog','Temp view живёт в session; Hive table переживает session и связывает metadata с HDFS.'),('NULL','WHERE оставляет только true; unknown отбрасывается. `<=>` реализует null-safe equality.'),('DDL','External/managed, LOCATION и overwrite задают жизненный цикл данных.'),('Диагностика','DESCRIBE EXTENDED, catalog API и EXPLAIN доказывают физический контракт.')],
'analytics':[('Grain','Перед JOIN назовите grain и кратность. N:M размножает строки и искажает суммы.'),('Aggregation','Предагрегируйте каждую деталь до ключа соединения.'),('Join','Broadcast малой стороны избегает shuffle; крупные стороны обычно требуют exchange и sort/hash.'),('Windows','Partition задаёт группу, order — последовательность, frame — диапазон вокруг строки.'),('Контроль','Сверяйте count, distinct key и суммы до и после JOIN.')],
'storage':[('Два смысла partition','Spark partition — task input, Hive partition — каталог по значению ключа.'),('Файлы','Мелкие файлы нагружают metadata/planning, слишком крупные ограничивают parallelism.'),('Parquet','Column pruning и row-group statistics уменьшают I/O.'),('Pruning','Явный фильтр partition column исключает каталоги до scan.'),('Запись','Append должен быть защищён от повтора; overwrite ограничивают нужной partition.')],
'performance':[('Планы','Parsed, analyzed, optimized logical и physical plan отвечают на разные вопросы.'),('Catalyst','Pushdown, pruning и constant folding работают для понятных engine выражений.'),('AQE','Runtime statistics позволяют сменить join, объединить shuffle partitions и обработать skew.'),('Memory','Cache материализуется action; spill означает перенос части работы на диск.'),('Benchmark','Сравнивайте одинаковый результат, прогревайте JVM и повторяйте измерение.')],
'quality_etl':[('Контракт','Schema, grain, key, NULL, domain, range и freshness должны стать executable checks.'),('Reject','Отклонённая строка сохраняет reason, исходные поля и run_id.'),('Идемпотентность','Повтор порции приводит к тому же target через overwrite partition или устойчивый merge.'),('Инкремент','Watermark фиксируют после publish, late data требует overlap/reprocessing.'),('Тесты','Проверяйте schema, ключи, множества строк и метрики, а не только count.')],
'capstone':[('Проектирование','До кода задайте grain, SLA, ключи, DQ, обновление и владельца.'),('Слои','raw→typed→accepted/reject→dimensions/fact→marts, каждый переход сверяется.'),('Физика','Partition, files, compression, cache и join strategy подтверждаются данными и plan.'),('Эксплуатация','Нужны run_id, rerun дня, late data, cleanup и мониторинг.'),('Приёмка','Докажите schema, uniqueness, reconciliation, pruning, plan и идемпотентность.')]
}
def md(x):return nbf.v4.new_markdown_cell(x)
def code(x):return nbf.v4.new_code_cell(x)
setup="""import os,sys\nsys.path.insert(0,'/opt/lab/spark-training')\nfrom check_task import check_task,save_evidence\nfrom pyspark.sql import SparkSession,functions as F,types as T,Window\nspark=SparkSession.builder.appName('spark-training').enableHiveSupport().getOrCreate()\nUSER=os.environ.get('HDFS_USER',os.environ.get('HADOOP_USER_NAME','student'))\nROOT=f'hdfs://namenode:8020/user/{USER}/spark_training'\nSOURCE='hdfs://namenode:8020/data/raw/ebay'\nebay=spark.read.parquet(SOURCE)\nprint('Spark',spark.version,'rows',ebay.count(),'columns',len(ebay.columns))"""
for no,key,title,raw in M:
 topics=raw.split('|'); theory='\n\n'.join(f'### {i}. {a}\n\n{b}' for i,(a,b) in enumerate(THEORY[key],1))
 cells=[md(f'# {title} — 30 заданий\n\nПрактика на eBay; решений нет.'),md('## Подробная теория\n\n'+theory),md('## Сдача\n\nКаждое задание записывает непустой Parquet в личный HDFS и evidence с transformation, observation и explanation. Checker использует активную SparkSession.'),code(setup)]
 for i,topic in enumerate(topics,1):
  cells += [md(f'### Задание {i}. {topic}\n\nСоздайте результат по теме **{topic}** и запишите `mode("overwrite").parquet(f"{{ROOT}}/{key}/task_{i:02d}")`. До action предскажите plan/число строк; после проверьте schema, ключи, NULL и partitions. Сохраните evidence.\n\n<details><summary>Подсказка</summary>\n\nНачните с минимального `ebay.select(...)`, вызовите `explain`, затем проверьте повторным чтением.\n\n</details>'),code('# Ваше решение\n# result = ...\n# result.write.mode("overwrite").parquet(...)\n# save_evidence(spark,...)'),code(f"check_task(spark,'{key}',{i})")]
 nbf.write(nbf.v4.new_notebook(cells=cells,metadata={'kernelspec':{'display_name':'Python 3 (ipykernel)','language':'python','name':'python3'}}),R/'notebooks'/f'{no}_{key}_30_Tasks.ipynb')
maps=[md('# Spark Course Map\n\n8 модулей, 240 заданий на Spark 3.5.5 и eBay.'),md('## Архитектура\n\n```text\nJupyter Driver → Spark Master → Worker 1 + Worker 2\n       └──────── HDFS + Hive Metastore ────────┘\n```'),md('## Данные\n\n2 501 511 строк, 24 колонки, grain `itemid` на `snapshot_dt`, Parquet/Snappy.'),md('## Модули\n\n'+'\n'.join(f'{i}. **{title}** — 30 заданий' for i,(_,_,title,_) in enumerate(M,1))),md('## Workflow\n\nТеория → прогноз plan → transformation → explain → action/write → повторное чтение → evidence → checker.')]
nbf.write(nbf.v4.new_notebook(cells=maps,metadata={'kernelspec':{'display_name':'Python 3 (ipykernel)','language':'python','name':'python3'}}),R/'notebooks'/'00_Spark_Course_Map.ipynb')
