-- TEMPLATE: replace the marker with real non-partition columns from printSchema().
-- CREATE EXTERNAL TABLE <USER_DB>.ebay_raw_parquet (
--   <REAL_COLUMNS_HERE>
-- ) PARTITIONED BY (snapshot_dt DATE)
-- STORED AS PARQUET LOCATION 'hdfs://namenode:8020/user/<USER>/ebay';
-- MSCK REPAIR TABLE <USER_DB>.ebay_raw_parquet;
