-- TEMPLATE: insert real eBay columns before executing.
-- CREATE EXTERNAL TABLE <USER_DB>.ebay_listings_optimized (
--   <REAL_COLUMNS_HERE>
-- ) PARTITIONED BY (snapshot_dt DATE)
-- STORED AS PARQUET
-- LOCATION 'hdfs://namenode:8020/user/<USER>/ebay_listings_optimized'
-- TBLPROPERTIES ('parquet.compression'='SNAPPY');
